### ISSUE TITLE
Support larger DSA keys

### ISSUE THREAD

**Issue by fmarier** [mozilla/browserid-local-verify#18]
If a user agent has enough power to generate and use larger DSA keys (e.g. native Persona support in Firefox desktop), then the verifier should honour them.

What needs to happen:

* add support for larger DSA keys in jwcrypto
* add support for larger DSA keys in the verifier library

/cc @warner

**Comment by rfk** [comment]
This repo is maintenance-only at this point; closing out old feature/enhancement bugs
