### ISSUE TITLE
Fails to trust the fallback on domain with a disabled support document

### ISSUE THREAD

**Issue by fmarier** [mozilla/browserid-local-verify#32]
When verifying an assertion issued by `login.persona.org` for an `@fmarier.org` email address (which has `disabled: true` in its [support document](https://fmarier.org/.well-known/browserid)), I get the following error message:

> untrusted issuer, expected 'fmarier.org', got 'login.persona.org'

**Comment by rfk** [comment]
This repo is maintenance-only at this point; closing out old feature/enhancement bugs
